rootProject.name = "ultpush"
include("ultpush-core")
include("ultpush-user")
include("ultpush-http")
include("ultpush-receiver-http")
include("ultpush-receiver-wework")
include("ultpush-receiver-webhook")
include("ultpush-handler-wework")
include("ultpush-handler-webhook")
include("ultpush-pusher-webhook")
include("ultpush-pusher-win")
include("ultpush-pusher-wework")
include("ultpush-pusher-http")
include("ultpush-http-javalin")
include("ultpush-configuration")
include("ultpush-configuration-jackson")
include("ultpush-bind")
