rootProject.name = "ultpush"
//push核心
include("ultpush-core")
//push的用户功能支持
include("ultpush-user")
//push的http服务支持
include("ultpush-http")
//push的企业微信支持
include("ultpush-wework")
//推送消息的win客户端支持
include("ultpush-pusher-win")
//push的基于Javalin的http服务实现
include("ultpush-http-javalin")
//push的配置文件支持
include("ultpush-configuration")
//push的基于Jackson的配置文件实现
include("ultpush-configuration-jackson")
//push的依赖架构绑定实现(基于Guice)
include("ultpush-bind")
include("ultpush-configuration-kotlinx-serialization")
